var FavoritePlaces = ["Canada", "Brazil", "Australia"];
console.log(FavoritePlaces);
console.log(FavoritePlaces.sort());
console.log(FavoritePlaces.sort().reverse());
console.log(FavoritePlaces.sort().reverse());
console.log(FavoritePlaces);
console.log(FavoritePlaces.sort());
console.log(FavoritePlaces.sort().reverse());
console.log(FavoritePlaces.sort());
console.log(FavoritePlaces.sort().reverse());
